# Generated by Django 3.1.1 on 2020-09-10 06:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200910_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
