# Generated by Django 3.1.1 on 2020-09-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eventcategory_index'),
        ('home', '0008_auto_20200915_1134'),
    ]

    operations = [
    ]
