# Generated by Django 3.1.1 on 2020-09-15 18:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200915_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.get_image_filename, verbose_name='First Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.get_image_filename, verbose_name='Second Image'),
        ),
    ]
