# Generated by Django 3.1.1 on 2020-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200915_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
