# Generated by Django 3.1.1 on 2020-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200923_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
